# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField()),
                ('rprev', models.IntegerField()),
                ('readdate', models.DateField()),
                ('rusage', models.IntegerField()),
                ('Connectioncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customers')),
            ],
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='connectioncode',
            new_name='connectionCode',
        ),
    ]
